language: node_js
node_js:
- '12.22.10'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=aprr)
  - secure: LUTFv8MLpp/EQngz80YYPf4obdAO6zaoOUKvbwwdXAMji6kUQqLYGOrfhSIHhK6kONEgJlMtGqASW4EijDUtmjybBwNkYFaYF7SiDJu84TDi2sttw+gGJXxrTZxo/+tvh97gMwXe8KXhiKzShP/ql5YezB7FxBKv6UaOco8J+LDILbXE1ILprZMvP63vAWTQZ1+fPmqD1DJvl/j4JzUUfsXahUj+oNjCFBu4q0ZfoeHNlpEdzbNclxN9ViH3/tZ7ekECujD3COWSMJCbmXEKI2hKjgRQdzGDVgz8jBSZ5plvmyQTOlHLCQtM76LirDiWREV9JTDmGNI5GfpDY4HrEYmLkKDeLdtumToY03EpaqM47lb6W0/NTYxGwrYPbc3Ex+klaCMJrjUi2C/QPoxyNNFmD+TCB+KbzhewILuJ/3fAIWHrQuY+kDPjuaC5FcdcnSMaA53qeuoLD9LeDzmbkOrG209bTe4P5DVRMull5yofz14lmO4LnORdVbbHdSnQDVibLfg9/ywqyZu3YdUZ9Gawd0ZrXcnG72boZotAA2USTF5mOQO3GrLWtmetD1O7MUpUEiRzBXaMnh3+g46BO7bSSOGVt+oW4/EAgRKeBsCUWy2zgOZqf59/UQUIq7RyEYwokOVG6hURgCABVJGFlJ4SVSMYwfYZVUEyr7NN7R0=
  # MATTERMOST_HOOK_URL
  - secure: NjvKoeFZKpJTRGhl674uz3xFLptoKWsfGwpEjMy8SpB/f0XFIDWf865IUn7TfG6cFb0xdgHy/gXEsGWTyUMsBDskqtfLI6KvlTSvJyPGg8cWgi/98NilNyTHNbnYE8uYrWEXivUCl2yqT2J1Y/5mE6YHISdwLYky6ikOBfMyrQ9AU1yQh2ibwnn2r2ToT74Ujl0412DiqB52pcJIIrPUQOT1pqkOD/fFFvgBYqVECRIyJl4WIUSXKAEmb8Eg7CyYOzThxK3SEGVPTnevNSUbHYyIBusTqdFfSqLhhP25OAJAKFoR1HB8qm/1rKeTLxaUJy8IYhRcP0b0bH8F+kaVfazRK5o8oGJT0Qi1EMorq/gdlFYV66b9CAoZCCOQfKE/PS2v6twREHremH4Tf8ucpQHqgRpGcJKHpCLQ+OaADBANGPPVoAGDNzvdOB9SnYLjCQc4tdY51/sQg0TOEO4b9YsDy4P+ET4cagHtV87MblTDb2hU4Ra+5P809oyR5o54UXbWeNBdYnLMuh2N148DtS1uyvbDFa0Xu2aL+xTRIX2MxCty5UPPooLvMeoS62fY/UoYAKn4gtcDwkf6c8JVXEjegKIJbgsQ7KEm540U1UEwxHFgXKJW44NulmHBS+jnUsc6NMvUyFlNPlqbKG0wmXLUrCXK7kHDizcSBPNG4wA=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_79893e17884d_key -iv $encrypted_79893e17884d_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
